### ISSUE TITLE
directories: avoid full `sort`

### ISSUE THREAD

**Issue by yarikoptic** [con/fscacher#19]
as initially briefly discussed in https://github.com/con/fscacher/pull/11#discussion_r524604069 

worth looking into how git does it as well

my guess (didn't try) that until we add support for #5 etc, it might just work without sort?

**Comment by jwodder** [comment]
I suspect (but can't find any explicit confirmation of, and separate confirmations would be required for every filesystem type) that the order of the items returned by `scandir()` only changes when there's a change to an entry somewhere in the directory tree, in which case it's likely that the fingerprint would change anyway.  If that's true, then the code should work automatically without `sort()`.  Additionally, ignoring files without `sort()` would only lead to problems if a change to an ignored file can cause the relative ordering of non-ignored files to change.
