### ISSUE TITLE
0.1 alpha release?

### ISSUE THREAD

**Issue by yarikoptic** [con/fscacher#22]
I think it is time -- we should start trying to use it.  API etc is sure thing a subject to change so should not be used "too widely"

how do we cut the first release (there is no prior pypi upload etc)

**Comment by jwodder** [comment]
@yarikoptic The first release is done the same way as any release: create a tag so that the version will be set, then just build the sdist & wheel and upload them to PyPI with Twine.  The README should probably be filled in first, though.

**Comment by yarikoptic** [comment]
oh, I thought that we had `auto` setup for this one already - but that initial tag was just for versioneer, my bad.  Should we do first release manually and then setup auto or the other way around?

**Comment by jwodder** [comment]
@yarikoptic I'd say first release manually, then `auto` after that.

**Comment by jwodder** [comment]
@yarikoptic To be clear: Is the version for this release supposed to be "0.1a", or is it just "0.1" and we keep considering the code to be in alpha state?

**Comment by yarikoptic** [comment]
as long as we can just `pip install fscacher` - any is good for me. marking it as alpha indeed makes good sense ;)

**Comment by jwodder** [comment]
@yarikoptic So 0.1a, then.

**Comment by jwodder** [comment]
@yarikoptic Released: https://pypi.org/project/fscacher/0.1a0/

I've invited you to be an owner on the PyPI project.

I think we should hold off on adding auto until after we've released a "final"/non-prerelease version, though.

**Comment by yarikoptic** [comment]
accepted, thank you!  I am ok with any path you consider the best here. I just got "too spoiled" by `auto` already, I guess ;)
