### ISSUE TITLE
conda-forge feedstock

### ISSUE THREAD

**Issue by yarikoptic** [con/fscacher#28]
process starts with submitting a PR against https://github.com/conda-forge/staged-recipes with the recipe with LICENSE and meta.yaml.

The process is quite simple, see any of the recent PRs there or the one we had for `dandi`: https://github.com/conda-forge/staged-recipes/pull/11289/files

After PR gets merged a dedicated repo would get generated for the feedstock, e.g. like https://github.com/conda-forge/dandi-feedstock and bots will submit PRs (to finalize or just merge) upon new releases appearing on pypi (apparently I have missed the one for dandi 0.10.0 heh: https://github.com/conda-forge/dandi-feedstock/pull/15 and it had some tests fail and now logs are gone :-/)

**Comment by jwodder** [comment]
PR: https://github.com/conda-forge/staged-recipes/pull/14015 (Please comment there confirming your status as a maintainer)

**Comment by yarikoptic** [comment]
done, thank you!

**Comment by jwodder** [comment]
fscacher is now on conda-forge.
