### ISSUE TITLE
tests started to fail - need troubleshooting/fixing

### ISSUE THREAD

**Issue by yarikoptic** [con/fscacher#94]
![image](https://github.com/con/fscacher/assets/39889/480a118e-bfb3-4fce-acce-19d214d0228b)

**Comment by jwodder** [comment]
@yarikoptic The failures occurred for the following reasons:

* On June 30, July 3, July 4, and July 7, the PyPy 3.8 job on Ubuntu (and also on macOS for July 3) raised a `pytest.PytestUnraisableExceptionWarning` in one test due to something involving weakrefs.
    * fscacher does not directly use weakrefs, so this is presumably due to a problem with joblib.

* On July 5, the CPython 3.8 job on Windows failed the `test_memoize_path` test due to a mismatch in the number of calls to a cached function.  I suspect this was due to a race condition involving `_min_dtime` being exceeded.
    * Possible resolutions:
        * Ignore the problem due to its rarity & instability
        * Apply `pytest-rerunfailures` to `test_memoize_path` (and possibly other tests) to automatically rerun the test up to a certain number of times if it fails

Note that, since this issue was created, only one of the thre scheduled CI jobs has failed.

**Comment by jwodder** [comment]
@yarikoptic Ping; what, if anything, should be done about this?

**Comment by yarikoptic** [comment]
it seems still to fail , although does pass some times
![image](https://github.com/con/fscacher/assets/39889/58899303-16fc-4823-93d6-7c222a2ec8b5)
so we do need to do something about it... here is the quick grep for what has failed (now we have fscacher CI logs cccccbhbnielgdgenkldjulbiuhjltklvdhdcjbhcrvk
on drogon):

```
dandi@drogon:/mnt/backup/dandi/tinuous-logs/fscacher/2024$ git -C 06 grep FAILED | grep '/test '
04/github/pr/93/02fa4b4/test.yml/1009-failed/test (windows-latest, pypy-3.8, py)/7_Run tests.txt:2024-06-04T15:29:55.4023702Z FAILED .tox/py/lib/site-packages/fscacher/tests/test_cache.py::test_memoize_path_persist
15/github/cron/20240615T061804/e52aaa0/test.yml/1020-failed/test (windows-latest, 3.9, py)/7_Run tests.txt:2024-06-15T06:19:18.5400930Z FAILED .tox/py/lib/site-packages/fscacher/tests/test_cache.py::test_memoize_path
20/github/cron/20240620T061943/e52aaa0/test.yml/1025-failed/test (windows-latest, pypy-3.8, py)/7_Run tests.txt:2024-06-20T06:22:15.3839278Z FAILED .tox/py/lib/site-packages/fscacher/tests/test_cache.py::test_memoize_path_dir
dandi@drogon:/mnt/backup/dandi/tinuous-logs/fscacher/2024$ git -C 07 grep FAILED | grep '/test '
03/github/cron/20240703T062139/e52aaa0/test.yml/1038-failed/test (macos-latest, pypy-3.8, py)/7_Run tests.txt:2024-07-03T06:23:23.4080810Z FAILED .tox/py/lib/pypy3.8/site-packages/fscacher/tests/test_cache.py::test_cache_control_envvar[ignore-clear-True-False]
05/github/cron/20240705T062054/e52aaa0/test.yml/1040-failed/test (windows-latest, 3.8, py)/7_Run tests.txt:2024-07-05T06:22:03.9025936Z FAILED .tox/py/lib/site-packages/fscacher/tests/test_cache.py::test_memoize_path
07/github/cron/20240707T061934/e52aaa0/test.yml/1042-failed/test (ubuntu-latest, pypy-3.8, py)/7_Run tests.txt:2024-07-07T06:20:30.2420866Z FAILED .tox/py/lib/pypy3.8/site-packages/fscacher/tests/test_cache.py::test_memoize_path_dir
10/github/cron/20240710T062013/e52aaa0/test.yml/1045-failed/test (windows-latest, pypy-3.8, py)/7_Run tests.txt:2024-07-10T06:22:32.1563327Z FAILED .tox/py/lib/site-packages/fscacher/tests/test_cache.py::test_memoize_path_dir
```

so may be we  just announce test_memoize_path_dir to xfail on 3.8 and 3.9 ?

**Comment by jwodder** [comment]
@yarikoptic

> so may be we just announce test_memoize_path_dir to xfail on 3.8 and 3.9 ?

Why 3.9?  I don't see any failures on 3.9.

Should the xfailing also be specific to PyPy, or should it apply on CPython as well?

**Comment by yarikoptic** [comment]
there was `(windows-latest, 3.9, py)` but I only now mentioned that it is for a different test -- `test_memoize_path` not `test_memoize_path_dir`.  May be xfail that one too on py and indeed only 3.8 pypy for test_memoize_path_dir

**Comment by yarikoptic** [comment]
> * I feel that that failure type would be better handled by `pytest-rerunfailures` than `pytest.mark.xfail`.

I have no objection on that.

> * Do you want me to apply xfail to all of them or do something else?  (Side note: While CPython supports 3.8 until October, PyPy hasn't supported 3.8 for about a year now.)

oh, let's just kick pypy 3.8 out then!
